import { type NextPage } from "next";
import Head from "next/head";

import { Home } from "components/components/main-page";

const Entry: NextPage = () => {
  return (
    <>
      <Head>
        <title>AI Search Engine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default Entry;
